services:
  mysql:
    extends:
      file: drive-infra/database/mysql/docker-compose.yml
      service: mysql
  redis:
    extends:
      file: drive-infra/database/redis/docker-compose.yml
      service: redis


