storage:
  type: ceph
  ceph:
    rgw:
#      end-point: http://192.168.10.102:9090
#      access-key: TR0JLCLPLQEX2LBJYMT5
#      secret-key: ZQltNNTamP82eNDgS19ANPsvUGz4UY5DVYBhlJ8V
      end-point: http://172.23.1.52:9000
      access-key: LH6WT0T7CWBACZXFYHAI
      secret-key: mCuL0ZYlzyf3Rnqe5doq9ML4s6bWNppyNj7aP1Ac
