spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE:tdrive}
#    username: "${MYSQL_USER:tdrive_user}"
#    password: "${MYSQL_PASSWORD:tdrive@1234}"
    url: jdbc:mysql://172.17.163.136:3306/tdrive
    username: tdrive_user
    password: Tdrive@$#21
    driver-class-name: com.mysql.cj.jdbc.Driver
